name: Sync to Hugging Face Hub
on:
  push:
    branches: [master]
  pull_request:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://ai-testack:$HF_TOKEN@huggingface.co/spaces/ai-testack/gpt-lib master:main
